language: node_js
node_js:
  - node
script:
  - node scripts/build.js
cache:
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: "AKIAJVZSDD6SWXNHMFCQ"
  secret_access_key: "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"
  bucket: "app.adhat-test.bucket"
  acl: public_read
  skip_cleanup: true
  local_dir: build_webpack
branches:
  only:
    - master
addons:
    apt:
      update: true